/* ==========================================================================
   lang.js
   ------------------------------------------------------------------------
   يتحكم في تبديل لغة الموقع (عربي / إنجليزي) واتجاه الصفحة (RTL / LTR).
   يعتمد على قاموس ترجمة كامل لكل عناصر [data-i18n] و [data-i18n-placeholder]
   ويحفظ اختيار المستخدم في localStorage ليبقى ثابتاً بين الصفحات.
   ========================================================================== */

(function () {
  "use strict";

  var STORAGE_KEY = "hope-lang";

  var DICT = {
    ar: {
      topbar_email: "info@charity-example.org",
      topbar_phone: "+249 000 000 000",
      topbar_hours: "السبت - الخميس: 9 ص - 5 م",
      nav_home: "الرئيسية",
      nav_about: "عن الجمعية",
      nav_projects: "مشاريعنا",
      nav_team: "الفريق والتنسيق",
      nav_contact: "تواصل معنا",
      nav_login: "تسجيل الدخول",
      nav_logout: "تسجيل الخروج",
      team_header_title: "الفريق والتنسيق",
      team_tag: "فريقنا",
      team_title: "تعرّف على الفريق القائم على تنفيذ برامجنا",
      team_text: "نخبة من المتخصصين والمتطوعين يعملون بشغف لتحقيق رسالة الجمعية",
      member1_role: "المدير التنفيذي",
      member2_role: "منسقة المشاريع",
      member3_role: "المسؤول المالي",
      member4_role: "منسق المتطوعين",
      coord_tag: "آلية العمل",
      coord_title: "كيف ننسّق جهودنا لضمان أقصى أثر",
      coord_text: "نعتمد على منهجية عمل واضحة تبدأ من دراسة الاحتياج الميداني، مروراً بالتخطيط المشترك مع الشركاء، وصولاً إلى التنفيذ والمتابعة وإصدار تقارير الأثر لكل مرحلة.",
      step1_title: "اختر مشروعاً",
      step2_title: "حدد مبلغ التبرع",
      step3_title: "أتمم العملية بأمان",
      step4_title: "تابع الأثر",
      partners_tag: "شركاؤنا",
      partners_title: "جهات تثق بنا وتدعم مسيرتنا",
      footer_about_title: "جمعية الأمل الخيرية",
      footer_about_text: "منظمة خيرية غير ربحية تعمل على تحسين حياة الأسر المحتاجة عبر برامج تعليمية وصحية وإغاثية مستدامة وشفافة.",
      footer_links_title: "روابط سريعة",
      footer_contact_title: "تواصل معنا",
      contact_addr_text: "الخرطوم، السودان - شارع النيل",
      footer_newsletter_title: "النشرة البريدية",
      footer_newsletter_text: "اشترك ليصلك كل جديد عن مشاريعنا وأنشطتنا",
      footer_newsletter_btn: "اشترك",
      footer_rights: "جميع الحقوق محفوظة",
      footer_privacy: "سياسة الخصوصية",
      footer_terms: "الشروط والأحكام",
      footer_credit: "تصميم وتطوير فريق جمعية الأمل",
      footer_newsletter_placeholder: "بريدك الإلكتروني",
      about_header_title: "عن جمعية الأمل الخيرية",
      about_story_tag: "قصتنا",
      about_story_title: "رحلة عطاء بدأت من إيمان بسيط",
      about_story_p1: "انطلقت الجمعية من مجموعة صغيرة من المتطوعين الذين آمنوا بأن التغيير يبدأ بخطوة.",
      about_story_p2: "نحرص في كل خطوة على الشفافية الكاملة في إدارة التبرعات، ونشر تقارير دورية توضح للمتبرعين أثر كل مساهمة قدموها.",
      mission_title: "رسالتنا",
      mission_text: "تقديم الدعم المستدام للفئات الأكثر احتياجاً عبر برامج تنموية وإغاثية شفافة وفعالة.",
      vision_title: "رؤيتنا",
      vision_text: "مجتمع خالٍ من الفقر والحاجة، يسوده التكافل والعطاء المستمر بين أفراده.",
      values_title: "قيمنا",
      values_text: "الشفافية - الأمانة - الاحترافية - احترام كرامة المستفيدين في كل برامجنا.",
      about_gallery_tag: "لمحة",
      about_gallery_title: "أبرز إنجازاتنا خلال السنوات الماضية",
      stats_beneficiaries: "مستفيد ومستفيدة",
      stats_volunteers: "متطوع نشط",
      stats_projects: "مشروع منجز",
      stats_years: "سنة من العطاء",
      contact_header_title: "تواصل معنا",
      contact_tag: "نحن هنا للاستماع إليك",
      contact_title: "تواصل مع فريق جمعية الأمل",
      contact_text: "يسعدنا تواصلكم معنا لأي استفسار أو اقتراح أو لبدء شراكة معنا",
      contact_addr_title: "العنوان",
      contact_phone_title: "الهاتف",
      contact_email_title: "البريد الإلكتروني",
      contact_hours_title: "ساعات العمل",
      contact_hours_text: "السبت - الخميس: 9 صباحاً - 5 مساءً",
      map_placeholder: "خريطة الموقع (يمكن استبدالها بخريطة Google حقيقية)",
      contact_form_title: "أرسل لنا رسالة",
      contact_form_text: "سيقوم فريقنا بالرد عليك خلال 24 ساعة",
      label_name: "الاسم الكامل",
      contact_error: "الرجاء التحقق من الحقول قبل الإرسال.",
      label_email: "البريد الإلكتروني",
      label_phone: "رقم الهاتف",
      label_subject: "الموضوع",
      label_message: "نص الرسالة",
      btn_send: "إرسال الرسالة",
      placeholder_name: "أدخل اسمك الكامل",
      placeholder_email: "example@email.com",
      placeholder_phone: "+249xxxxxxxxx",
      placeholder_subject: "موضوع رسالتك",
      placeholder_message: "اكتب رسالتك هنا بالتفصيل...",
      projects_header_title: "مشاريعنا",
      proj1_tag: "تعليم",
      proj1_title: "كفالة أيتام للتعليم",
      proj1_text: "توفير الرسوم الدراسية والأدوات المدرسية لـ 500 طفل يتيم سنوياً",
      proj_raised: "تم جمعه",
      proj_target: "الهدف",
      proj_btn: "ادعم المشروع",
      proj2_tag: "صحة",
      proj2_title: "قوافل طبية مجانية",
      proj2_text: "تنظيم قوافل طبية دورية للمناطق النائية التي تفتقر للخدمات الصحية",
      proj3_tag: "إغاثة",
      proj3_title: "سلال غذائية للأسر المحتاجة",
      proj3_text: "توزيع سلال غذائية شهرية على أكثر من 1000 أسرة محتاجة",
      proj4_tag: "تعليم",
      proj4_title: "بناء مدرسة نموذجية",
      proj4_text: "إنشاء مدرسة مجهزة بالكامل تخدم أطفال القرى المحيطة",
      proj5_tag: "صحة",
      proj5_title: "دعم مرضى الفشل الكلوي",
      proj5_text: "تغطية تكاليف جلسات الغسيل الكلوي للأسر غير القادرة",
      proj6_tag: "إغاثة",
      proj6_title: "مأوى مؤقت لمنكوبي الكوارث",
      proj6_text: "توفير خيام ومستلزمات إيواء أساسية لضحايا الكوارث الطبيعية",
      proj7_tag: "مياه",
      proj7_title: "حفر آبار مياه نظيفة",
      proj7_text: "حفر وصيانة آبار مياه نظيفة لتوفير مصدر مياه شرب آمن للقرى النائية",
      proj8_tag: "تمكين",
      proj8_title: "تمكين المرأة اقتصادياً",
      proj8_text: "تدريب النساء المعيلات على حرف مهنية ومنحهن قروضاً صغيرة لبدء مشاريعهن الخاصة",
      proj9_tag: "إغاثة",
      proj9_title: "كسوة الشتاء للأسر المحتاجة",
      proj9_text: "توزيع ملابس وبطانيات شتوية دافئة على الأسر الأكثر احتياجاً قبل حلول البرد",
      cta_title: "لا تتردد.. كل لحظة تأخير قد تكلف أسرة أملها",
      cta_text: "انضم إلى مجتمع الداعمين وكن جزءاً من قصص النجاح القادمة",
      cta_btn: "تبرّع الآن",
      welcome_back: "مرحباً بعودتك",
      logged_in_as: "أنت مسجل الدخول باسم",
      go_home: "العودة للرئيسية",
      btn_logout_full: "تسجيل الخروج",
      tab_login: "تسجيل الدخول",
      tab_register: "حساب جديد",
      login_header_title: "تسجيل الدخول",
      login_demo_hint: "بيانات تجريبية: admin / admin123",
      label_username: "اسم المستخدم أو البريد الإلكتروني",
      login_error: "اسم المستخدم أو كلمة المرور غير صحيحة.",
      label_password: "كلمة المرور",
      remember_me: "تذكرني",
      forgot_password: "نسيت كلمة المرور؟",
      btn_login: "دخول",
      login_footer_text: "ليس لديك حساب؟",
      login_footer_link: "أنشئ حساباً الآن",
      label_confirm_password: "تأكيد كلمة المرور",
      btn_register: "إنشاء الحساب",
      register_footer_text: "لديك حساب بالفعل؟",
      register_footer_link: "سجّل الدخول",
      placeholder_username: "أدخل اسم المستخدم أو البريد",
      placeholder_password: "••••••••",
      hero_badge: "معاً نصنع فرقاً حقيقياً",
      hero_title: "جمعية الأمل الخيرية.. يد العطاء التي لا تتوقف",
      hero_text: "نعمل منذ سنوات على تقديم الدعم للأسر المحتاجة عبر مشاريع تنموية وإغاثية مستدامة، وكل تبرع منكم يصنع فرقاً حقيقياً في حياة أسرة كاملة.",
      hero_btn_donate: "ابدأ التبرع",
      hero_btn_projects: "تصفح المشاريع",
      hero_visual_title: "أثرك يبدأ من هنا",
      hero_visual_text: "كل ريال تتبرع به يُدار بشفافية كاملة ويصل مباشرة إلى مستحقيه عبر فريق ميداني مدرّب.",
      about_home_tag: "من نحن",
      about_home_title: "قصة جمعية بدأت بفكرة وكبرت بالعطاء",
      about_home_text: "تأسست الجمعية بهدف سد الفجوة بين أصحاب النوايا الطيبة والأسر المحتاجة، من خلال برامج شفافة ومستدامة تغطي التعليم والصحة والإغاثة الطارئة.",
      about_home_btn: "اقرأ المزيد عنا",
      projects_home_tag: "مشاريعنا",
      projects_home_title: "مشاريع نفخر بها ونحتاج دعمكم لاستمرارها",
      projects_home_text: "مجموعة من المشاريع الحيوية التي تلامس حياة آلاف الأسر يومياً",
      steps_tag: "كيف تساعد",
      steps_title: "طريقك للمساهمة في 4 خطوات بسيطة",
      step1_text: "تصفح قائمة المشاريع النشطة واختر ما يناسب اهتمامك",
      step2_text: "اختر المبلغ المناسب لك، كل مبلغ مهما كان بسيطاً له أثر",
      step3_text: "ادفع عبر بوابات دفع آمنة ومعتمدة بكل سهولة",
      step4_text: "استلم تقارير دورية توضح أثر تبرعك على أرض الواقع"
    },
    en: {
      topbar_email: "info@charity-example.org",
      topbar_phone: "+249 000 000 000",
      topbar_hours: "Sat - Thu: 9 AM - 5 PM",
      nav_home: "Home",
      nav_about: "About Us",
      nav_projects: "Our Projects",
      nav_team: "Team & Coordination",
      nav_contact: "Contact Us",
      nav_login: "Login",
      nav_logout: "Logout",
      team_header_title: "Team & Coordination",
      team_tag: "Our Team",
      team_title: "Meet the team behind our programs",
      team_text: "A group of dedicated specialists and volunteers working passionately to fulfill our mission",
      member1_role: "Executive Director",
      member2_role: "Projects Coordinator",
      member3_role: "Financial Officer",
      member4_role: "Volunteers Coordinator",
      coord_tag: "How We Work",
      coord_title: "How we coordinate our efforts for maximum impact",
      coord_text: "We follow a clear methodology that starts with assessing field needs, moves through joint planning with partners, and continues through implementation, follow-up, and impact reports at every stage.",
      step1_title: "Choose a Project",
      step2_title: "Set Your Donation",
      step3_title: "Complete Securely",
      step4_title: "Track the Impact",
      partners_tag: "Our Partners",
      partners_title: "Organizations that trust and support our journey",
      footer_about_title: "Hope Charity Association",
      footer_about_text: "A non-profit organization working to improve the lives of families in need through sustainable and transparent educational, health, and relief programs.",
      footer_links_title: "Quick Links",
      footer_contact_title: "Contact Us",
      contact_addr_text: "Khartoum, Sudan - Nile Street",
      footer_newsletter_title: "Newsletter",
      footer_newsletter_text: "Subscribe to get the latest news about our projects and activities",
      footer_newsletter_btn: "Subscribe",
      footer_rights: "All rights reserved",
      footer_privacy: "Privacy Policy",
      footer_terms: "Terms & Conditions",
      footer_credit: "Designed & developed by the Hope Association team",
      footer_newsletter_placeholder: "Your email address",
      about_header_title: "About Hope Charity Association",
      about_story_tag: "Our Story",
      about_story_title: "A journey of giving that began with a simple belief",
      about_story_p1: "The association started with a small group of volunteers who believed that change begins with a single step.",
      about_story_p2: "We ensure full transparency in managing donations at every step, publishing regular reports that show donors the real impact of every contribution.",
      mission_title: "Our Mission",
      mission_text: "Providing sustainable support to the most vulnerable groups through transparent and effective development and relief programs.",
      vision_title: "Our Vision",
      vision_text: "A community free of poverty and need, built on solidarity and continuous giving among its members.",
      values_title: "Our Values",
      values_text: "Transparency - Integrity - Professionalism - Respecting the dignity of beneficiaries in all our programs.",
      about_gallery_tag: "Glimpse",
      about_gallery_title: "Our key achievements over the past years",
      stats_beneficiaries: "Beneficiaries",
      stats_volunteers: "Active Volunteers",
      stats_projects: "Completed Projects",
      stats_years: "Years of Giving",
      contact_header_title: "Contact Us",
      contact_tag: "We're Here to Listen",
      contact_title: "Get in touch with the Hope team",
      contact_text: "We'd love to hear from you for any inquiry, suggestion, or partnership",
      contact_addr_title: "Address",
      contact_phone_title: "Phone",
      contact_email_title: "Email",
      contact_hours_title: "Working Hours",
      contact_hours_text: "Sat - Thu: 9 AM - 5 PM",
      map_placeholder: "Location map (can be replaced with a real Google Map)",
      contact_form_title: "Send Us a Message",
      contact_form_text: "Our team will respond within 24 hours",
      label_name: "Full Name",
      contact_error: "Please check the fields before submitting.",
      label_email: "Email",
      label_phone: "Phone Number",
      label_subject: "Subject",
      label_message: "Message",
      btn_send: "Send Message",
      placeholder_name: "Enter your full name",
      placeholder_email: "example@email.com",
      placeholder_phone: "+249xxxxxxxxx",
      placeholder_subject: "Your message subject",
      placeholder_message: "Write your message in detail...",
      projects_header_title: "Our Projects",
      proj1_tag: "Education",
      proj1_title: "Orphan Education Sponsorship",
      proj1_text: "Covering tuition fees and school supplies for 500 orphaned children every year",
      proj_raised: "Raised",
      proj_target: "Target",
      proj_btn: "Support This Project",
      proj2_tag: "Health",
      proj2_title: "Free Medical Convoys",
      proj2_text: "Organizing regular medical convoys to remote areas lacking healthcare services",
      proj3_tag: "Relief",
      proj3_title: "Food Baskets for Families in Need",
      proj3_text: "Distributing monthly food baskets to over 1,000 families in need",
      proj4_tag: "Education",
      proj4_title: "Building a Model School",
      proj4_text: "Constructing a fully-equipped school serving children of surrounding villages",
      proj5_tag: "Health",
      proj5_title: "Support for Kidney Failure Patients",
      proj5_text: "Covering dialysis session costs for families who cannot afford them",
      proj6_tag: "Relief",
      proj6_title: "Temporary Shelter for Disaster Victims",
      proj6_text: "Providing tents and essential shelter supplies for natural disaster victims",
      proj7_tag: "Water",
      proj7_title: "Clean Water Wells",
      proj7_text: "Drilling and maintaining clean water wells to provide a safe drinking source for remote villages",
      proj8_tag: "Empowerment",
      proj8_title: "Women's Economic Empowerment",
      proj8_text: "Training breadwinning women in professional skills and offering micro-loans to launch their own small businesses",
      proj9_tag: "Relief",
      proj9_title: "Winter Clothing for Families in Need",
      proj9_text: "Distributing warm winter clothes and blankets to the most vulnerable families before the cold sets in",
      cta_title: "Don't wait.. every moment of delay could cost a family its hope",
      cta_text: "Join our community of supporters and be part of the next success stories",
      cta_btn: "Donate Now",
      welcome_back: "Welcome Back",
      logged_in_as: "You're logged in as",
      go_home: "Back to Home",
      btn_logout_full: "Log Out",
      tab_login: "Login",
      tab_register: "New Account",
      login_header_title: "Login",
      login_demo_hint: "Demo credentials: admin / admin123",
      label_username: "Username or Email",
      login_error: "Incorrect username or password.",
      label_password: "Password",
      remember_me: "Remember Me",
      forgot_password: "Forgot Password?",
      btn_login: "Login",
      login_footer_text: "Don't have an account?",
      login_footer_link: "Create One Now",
      label_confirm_password: "Confirm Password",
      btn_register: "Create Account",
      register_footer_text: "Already have an account?",
      register_footer_link: "Login",
      placeholder_username: "Enter username or email",
      placeholder_password: "••••••••",
      hero_badge: "Together We Make a Real Difference",
      hero_title: "Hope Charity Association.. A Hand of Giving That Never Stops",
      hero_text: "For years we've supported families in need through sustainable development and relief projects, and every donation you make creates a real difference in a whole family's life.",
      hero_btn_donate: "Start Donating",
      hero_btn_projects: "Browse Projects",
      hero_visual_title: "Your Impact Starts Here",
      hero_visual_text: "Every dollar you donate is managed with full transparency and reaches those in need directly through a trained field team.",
      about_home_tag: "About Us",
      about_home_title: "A story that began with an idea and grew through giving",
      about_home_text: "The association was founded to bridge the gap between well-intentioned donors and families in need, through transparent, sustainable programs covering education, health, and emergency relief.",
      about_home_btn: "Read More About Us",
      projects_home_tag: "Our Projects",
      projects_home_title: "Projects we're proud of and need your support to continue",
      projects_home_text: "A set of vital projects that touch the lives of thousands of families every day",
      steps_tag: "How to Help",
      steps_title: "Your path to contributing in 4 simple steps",
      step1_text: "Browse the list of active projects and choose what interests you",
      step2_text: "Choose the amount that suits you, every amount makes a difference",
      step3_text: "Pay easily through secure, trusted payment gateways",
      step4_text: "Receive regular reports showing the real impact of your donation"
    }
  };

  function getLang() {
    try {
      return localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "ar";
    } catch (e) {
      return "ar";
    }
  }

  function applyLang(lang) {
    var dict = DICT[lang] || DICT.ar;
    var html = document.documentElement;

    html.setAttribute("lang", lang);
    html.setAttribute("dir", lang === "en" ? "ltr" : "rtl");

    document.querySelectorAll("[data-i18n]").forEach(function (el) {
      var key = el.getAttribute("data-i18n");
      if (dict[key] !== undefined) {
        el.textContent = dict[key];
      }
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
      var key = el.getAttribute("data-i18n-placeholder");
      if (dict[key] !== undefined) {
        el.setAttribute("placeholder", dict[key]);
      }
    });

    document.querySelectorAll(".lang-btn-text").forEach(function (el) {
      el.textContent = lang === "en" ? "العربية" : "English";
    });

    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch (e) {}
  }

  function toggleLang() {
    applyLang(getLang() === "en" ? "ar" : "en");
  }

  // إتاحة الدوال عالمياً حتى تُستخدم من main.js وأزرار onclick المضمّنة
  window.getLang = getLang;
  window.applyLang = applyLang;
  window.i18nDict = DICT;

  document.addEventListener("DOMContentLoaded", function () {
    applyLang(getLang());
    document.querySelectorAll(".lang-switch").forEach(function (btn) {
      btn.addEventListener("click", toggleLang);
    });
  });
})();
